### ISSUE TITLE
Minor issues of q3dfit outfput and line_plot

### ISSUE THREAD

**Issue by WujiWang-astro** [Q3D/q3dfit#13]
Hi David,

I spotted two minor issues, but they did not impede the overall performance of q3dfit. Just to note down:

1. When extracting the output of the fit results, using q3do.line_fitpars['flux'], the unit of the integrated flux is not always 'correct'. I checked the source code and found that the 'problem' is in q3dout.py, line 356 to 373. The unit of the flux density is what we have from the input specified by the user and the wavelength unit is also passed from the original input of the spectrum. However, this will cause a problem, say if the flux density input was erg/s/cm2/Angstrom but the wavelength unit is micron, the integrated unit is just simply erg/s/cm2/Angstrom*micron. This is not entirely wrong but not transparent and may cause some confusion.

2. When using the q3do.plot_line function to save the plot, the 'outfile' (plot.py line 843) seems not to be the one specified by the user in the argument of q3do.plot_line function. That is to say, if I use q3do.plot_line(outfile='XXX') and print it in line 843 of plot.py, the result is NOT XXX but the outdir path string specified at the q3din stage. This is a minor thing, I haven't checked what is the cause of this or if this is only my local problem.

Cheers,
Wuji

**Comment by drupke** [comment]
Wuji, I believe I have fixed these issues in v1.1.1, just published. Cube is now more verbose about flux/wavelength units and some of the logic shifted a bit. If you input `erg/s/cm2/Angstrom` as `waveunit_in` it will actually convert to `erg/s/cm2/micron`. However, if you also set `waveunit_out = erg/s/cm2/Angstrom` you run into the issue you describe. Rather than correct this, hopefully the more verbose description will now alert the user that the result will be an integrated flux unit that's a little odd. `plot_line` (and `plot_cont`) will now use the file specified in `outfile` and *then* revert to the default set by `load_q3dout`.
